FROM openjdk:17
WORKDIR /app-java
ARG PORT=8090
ENV PORT=$PORT
ENV MONGO_NAME_HOST=mongo
ENV MONGO_PORT_HOST=27017
ENV MONGO_NAME_DB=barber
ENV MONGO_USERNAME=barber
ENV MONGO_PASSWORD=senha123
ENV SECRET-JWT=$2a$12$AR7.Mr3k13kuZUM5wYzqvO64oprB1aCOBWIXEFDejCP7x2DAjSTbi
COPY . /app-java
CMD ["./mvnw", "spring-boot:run"]
